# Generated by Django 2.2.12 on 2020-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200601_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='dummy desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(default='tag1 taggy2 idktag3'),
            preserve_default=False,
        ),
    ]
