# Generated by Django 2.2.12 on 2020-06-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_article_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='desk', max_length=200),
            preserve_default=False,
        ),
    ]
